// Read/write the single-row settings store. Used by the LLM prompt
// builders to layer brand/voice/length config on top of env vars.
//
// Reading is "settings table → env var → hard default", so an env var
// (e.g. SITE_CTA) is the fallback if the DB row isn't set yet. This
// preserves the original behaviour for installs that haven't touched
// the settings page.
import { nowSec } from './util.js';

const FALLBACK = {
  site_cta:         (env) => env.SITE_CTA || 'Sign up to get started.',
  site_tone:        (_)   => '',
  site_audience:    (_)   => '',
  site_signup_url:  (env) => env.SITE_SIGNUP_URL || '/signup',
  site_pricing_url: (env) => env.SITE_PRICING_URL || '/pricing',
  site_contact_url: (env) => env.SITE_CONTACT_URL || '/contact',
  // Length targets for the daily blog generator. Bumped from 900-1300
  // in v1.0.2 to bias toward definitive long-form pieces, which rank
  // better for long-tail queries and have more share value. Operators
  // who want short posts can edit these in /admin → Settings.
  article_min_words:   () => '2500',
  article_max_words:   () => '4000',
  prog_min_words:      () => '700',
  prog_max_words:      () => '1000',
  default_ai_provider: () => '',
  // Brand DNA — generated from the user's own site, editable in the
  // admin UI. Plugged into every prompt so the LLM writes as if it
  // works for that business.
  brand_business_type:     () => '',
  brand_voice_tone:        () => '',
  brand_target_audience:   () => '',
  brand_key_themes:        () => '', // newline- or comma-separated
  brand_topics_to_avoid:   () => '',
  brand_service_area:      () => '',
  brand_source_url:        () => '', // the URL we scraped (informational)
  brand_generated_at:      () => '', // ISO timestamp of last generation
  // Onboarding wizard completion flag. Empty until the first admin
  // signs off the wizard; we use that to decide whether to launch the
  // wizard on next login. Set explicitly via /api/admin/onboarding so
  // re-running the wizard requires intent (operator opens it from the
  // help menu).
  onboarding_complete:     () => '',
  // Admin token used as the HMAC secret for session cookies, the
  // bearer-token recovery path, and the AES-GCM key for the secret
  // vault. Empty by default; set either via the Pages secret
  // ADMIN_TOKEN (CLI install path) or generated by /api/setup on
  // first run (one-click deploy path). Resolved via _lib/admin_token.js.
  admin_token:             () => '',
  // SITE_NAME / SITE_URL can also live in D1 (set by /api/setup on the
  // one-click deploy path). The Pages secret takes precedence.
  site_name_db:            () => '',
  site_url_db:             () => '',
  // Update-check metadata. Written when the operator installs from
  // /install (browser path) so the Updates admin tab can compare the
  // installed commit to upstream HEAD and offer a one-click rebuild.
  install_method:          () => '',   // 'browser' | 'cli' | ''
  // One-time setup-magic-link token. The browser installer sets this
  // as a Pages env var (SETUP_TOKEN); the legacy in-app form falls
  // back to reading it from settings if the env var is unset.
  // /api/setup consumes it on success by setting onboarding_complete.
  setup_token:             () => '',
  installed_sha:           () => '',   // upstream main commit SHA at install time
  install_repo_owner:      () => '',   // user's GitHub fork owner
  install_repo_name:       () => '',   // user's GitHub fork repo name
  install_cf_account:      () => '',   // user's Cloudflare account id (no secrets)
  install_cf_project:      () => '',   // user's Pages project slug
  install_cf_token:        () => '',   // user's CF API token, encrypted via secret_vault
  // Last time the user dismissed an "update available" badge — used to
  // re-show after a fresh upstream commit (compared against latest sha).
  update_dismissed_sha:    () => '',
  // How the daily blog chain produces its hero image.
  //   'ai'     = generate a fresh image with the AI provider (current default)
  //   'cover'  = render a saved cover template (uses the default template + post title)
  // When 'ai', the Covers tab is shown but frozen with an explainer.
  hero_image_mode:         () => 'ai',
  // Cached LLM price catalogue (JSON). Refreshed via the Settings tab
  // from models.dev. See functions/_lib/prices.js.
  price_cache_json:        () => '',
  // Usage + budget. Cost values are USD per 1M tokens, separate input
  // and output rates. Prices come from prices.js (bundled snapshot +
  // optional models.dev cache) rather than per-key settings.
  monthly_budget_usd:      () => '10',     // hard-stop cron when this month's spend >= this
  budget_warn_pct:         () => '80',     // show banner at this % of budget

  // Search-engine verification. Both are optional strings the user
  // pastes in once they've claimed the property in Search Console /
  // Bing Webmaster Tools. The renderer emits these as meta tags on
  // every blog + programmatic page so the meta-file verification
  // path works without manual file uploads to R2.
  //
  //   google_site_verification: the value from <meta name="google-
  //   site-verification" content="…"> in the GSC "Add property →
  //   HTML tag" flow. Leave empty to skip.
  //   bing_site_verification: same for Bing's msvalidate.01 meta.
  google_site_verification: () => '',
  bing_site_verification:   () => '',

  // Google Search Console auto-indexing. Sitemap re-submit is
  // the safe ToS-compliant default — fires on every publish and
  // tells GSC to re-crawl /sitemap.xml. The Indexing API path
  // (toggle: '1') POSTs each URL directly for faster pickup, but
  // Google officially only supports it for JobPosting and
  // BroadcastEvent schema; using it for blogs typically works but
  // violates ToS.
  //
  //   google_sc_property      — the property string in GSC (e.g.
  //                              'sc-domain:example.com' for
  //                              domain-property installs, or
  //                              'https://example.com/' for URL-prefix).
  //                              Auto-derived from SITE_URL if empty.
  //   google_use_indexing_api — '1' to also POST per-URL to the
  //                              Indexing API. Default '' (off).
  //
  // The service-account JSON lives in the vault under
  // 'GOOGLE_SA_JSON' (set via /api/admin/settings — never in D1
  // settings table directly).
  google_sc_property:        () => '',
  google_use_indexing_api:   () => '',

  // Brand identity for cover templates + JSON-LD. The cover renderer
  // exposes these as {brand.tagline}, {brand.logo_url}, {brand.
  // primary_color}, {brand.accent_color} so the same template can
  // produce different visual identities on different installs without
  // editing the spec.
  //
  //   site_tagline           — short subtitle shown under the brand name
  //                            ("daily SEO articles", "shop fashion online")
  //   brand_logo_url         — absolute URL to a small logo image (PNG/SVG)
  //                            used in the corner of cover templates.
  //                            Leave empty if you don't want one.
  //   brand_primary_color    — hex string, used as default fill on box
  //                            layers ({brand.primary_color}).
  //   brand_accent_color     — hex string, used as accent/highlight on
  //                            cover templates ({brand.accent_color}).
  site_tagline:         () => '',
  brand_logo_url:       () => '',
  brand_primary_color:  () => '#0a0c10',
  brand_accent_color:   () => '#d4af62',
};

const KEYS = Object.keys(FALLBACK);

// Per-request memoisation.
//
// `loadSettings` reads the ENTIRE settings table (35 rows here). A single blog
// page view calls it from the renderer and again from whatever helper needs
// site identity, and every one of those calls re-reads all 35 rows — D1 bills
// per row read, so this is the single biggest avoidable cost on the public
// path.
//
// The cache lives on `env`, which is one object per request in Pages Functions,
// so it cannot leak between requests or between tenants. Same pattern as
// CACHE_KEY in project_scope.js.
const SETTINGS_CACHE_KEY = '__ps_settings_cache__';

export function invalidateSettingsCache(env) {
  if (env) delete env[SETTINGS_CACHE_KEY];
}

export async function loadSettings(env) {
  if (env?.[SETTINGS_CACHE_KEY]) return env[SETTINGS_CACHE_KEY];

  const out = {};
  try {
    const rows = await env.DB.prepare('SELECT key, value FROM settings').all();
    for (const row of (rows?.results || [])) {
      if (row.value != null) out[row.key] = row.value;
    }
  } catch {
    // table missing or DB unavailable — fall through to env fallbacks
  }
  for (const k of KEYS) {
    if (out[k] == null || out[k] === '') out[k] = FALLBACK[k](env);
  }

  // Derived aliases. site_name / site_url are read in lots of
  // legacy call sites; resolve them from (env first, then D1) so
  // CLI installs (Pages secret) AND 1-click Deploy installs (D1
  // row) both work without each call site duplicating the logic.
  out.site_name = (env?.SITE_NAME || '').trim() || out.site_name_db || '';
  out.site_url  = (env?.SITE_URL  || '').trim() || out.site_url_db  || '';

  // Only cache a successful read. If the query threw, the fallbacks above are
  // still a usable answer for this call, but caching them would pin a broken
  // read for the rest of the request even if the DB recovers.
  if (env && out && Object.keys(out).length) {
    try { env[SETTINGS_CACHE_KEY] = out; } catch { /* frozen env */ }
  }

  return out;
}

export async function setSetting(env, key, value) {
  if (!KEYS.includes(key)) throw new Error('unknown_setting: ' + key);
  const t = nowSec();
  await env.DB.prepare(
    `INSERT INTO settings (key, value, updated_at) VALUES (?, ?, ?)
     ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at`
  ).bind(key, value == null ? '' : String(value), t).run();
  // A write must not leave a stale memoised read behind — otherwise an
  // endpoint that saves a setting and then reads it back within the same
  // request would see the old value.
  invalidateSettingsCache(env);
}

export function listSettingKeys() { return [...KEYS]; }
